openapi: 3.0.2
info:
    title: Locations
    version: 1.0.0
    description: Locations API
paths:
    /locations:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/location'
                            example: |-
                                [
                                  {
                                    "id": 1,
                                    "name": "Kamarhati",
                                    "type": "Regional Branch",
                                    "status": "1",
                                    "location": {
                                      "lat": "-28.32555",
                                      "lng": "-5.91531"
                                    }
                                  },
                                  {
                                    "id": 2,
                                    "name": "Otranto",
                                    "type": "Local Office",
                                    "status": "1",
                                    "location": {
                                      "lat": "-8.01254",
                                      "lng": "101.47364"
                                    }
                                  },
                                  {
                                    "id": 3,
                                    "name": "Millesimo",
                                    "type": "Headquarter",
                                    "status": "1",
                                    "location": {
                                      "lat": "78.88435",
                                      "lng": "99.05294"
                                    }
                                  }
                                ]
                    description: Successful response
        post:
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/location'
                    description: Successfully created
    '/locations/{id}':
        get:
            parameters:
                -
                    name: id
                    schema:
                        format: int32
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/location'
                    description: Successful response
    '/location/phone/{id}':
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/location'
                    description: Successful response
        parameters:
            -
                name: id
                schema:
                    format: int32
                    type: integer
                in: path
                required: true
components:
    schemas:
        location:
            title: Root Type for location
            description: The root of the location type's schema.
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                type:
                    type: string
                status:
                    format: int32
                    type: integer
                location:
                    type: object
                    properties:
                        lat:
                            type: string
                        lng:
                            type: string
            example: |-
                {
                  "id": 1,
                  "name": "Kamarhati",
                  "type": "Regional Branch",
                  "status": "1",
                  "location": {
                    "lat": "-28.32555",
                    "lng": "-5.91531"
                  }
                }
